export const ADD_ITEM = 'ADD_ITEM_TO_CART';
export const ADD_QUANITY = 'ADD_ITEM_TO_CART_QUANITY';
export const REMOVE_ITEM = 'REMOVE_ITEM_FROM_CART';
export const REMOVE_QUANITY = 'REMOVE_ITEM_QUANITY_FROM_CART';
export const CURRENT_ITEM = 'CURRENT_SELECTED_ITEM';